### ISSUE TITLE
Crash when containers directory is empty. plz2fx

### ISSUE THREAD

**Issue by Onager** [google/docker-explorer#87]
```
# /home/onager/.local/bin/de.py -r /media/disk/var/lib/docker/ list all_containers
Could not find container directoried in /media/disk/var/lib/docker/containers.
Make sure the docker directory (/media/disk/var/lib/docker/) is correct.
If it is correct, you might want to run this script with higher privileges.
Traceback (most recent call last):
  File "/home/onager/.local/bin/de.py", line 185, in <module>
    DockerExplorerTool().Main()
  File "/home/onager/.local/bin/de.py", line 162, in Main
    self._explorer.DetectDockerStorageVersion()
  File "/home/onager/.local/lib/python2.7/site-packages/docker_explorer/explorer.py", line 76, in DetectDockerStorageVersion
    self.containers_directory, container_ids_list[0])
IndexError: list index out of range
```
Containers directory is present, but empty

**Comment by rgayon** [comment]
Let's have a proper exception + message
